<h2>Note Creation</h2>

<?php

$form->setAttribute('action', $this->url('notes/create'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('user_id'));
?>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('title'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('content'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
</div>