<h2>Edit page</h2>

<?php

$form->setAttribute('action', $this->url('notes/edit', ['id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('user_id'));
?>
<div class="form-group form-group-btn">
    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('title'));
    ?>
</div>

<div class="form-group">
    <?php
    echo $this->formRow($form->get('content'));
    ?>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function() {
        var txtarea = document.querySelector("textarea.form-control");
        txtarea.style.minHeight = (txtarea.scrollHeight + 5) + "px"

    });
</script>

<script>
    var txtAreas = document.querySelectorAll('.autoTxtArea');
    txtAreas[x].addEventListener('input', function() {
        if (this.scrollHeight > this.offsetHeight) this.rows += 1;
    });
</script>