<h2>Edit page</h2>

<?php

$form->setAttribute('action', $this->url('notes/edit', ['id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('user_id'));
echo $this->formHidden($form->get('content'));

?>
<div class="form-group form-group-btn">
    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('title'));
    ?>
</div>

<div class="form-group">
    <label for="txtArea">Content:</label>
    <div contenteditable="true" name="htmlContent" id="htmlContent" class="form-control txtArea" style="display: inline-block"></div>
</div>

<div>
    <button id="butt">B</button>
</div>

<script src="<?= $this->basePath('js/prettier_txt.js') ?>"></script>