<?= $this->headTitle('Listing - Notes') ?>

<h1>Notes Listing</h1>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Are you sure you want to delete this item?</h5><button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
            </div>
            <input type="hidden" name="note_id" id="note_id" value="">
            <div class="modal-footer">
                <a id="dataConfirm"><button type="button" class="btn btn-danger">Delete</button></a>
                <button type="button" class="btn btn-primary" data-dismiss="modal" aria-label="Close">Cancel</button>
            </div>
        </div>
    </div>
</div>

<?php
if (count($notes) > 0) : ?>
    <a href="<?= $this->url('notes/create') ?>" class="btn btn-outline-primary btn-lg btn-create"> Create note</a>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Content</th>
                <th scope="col">Buttons</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($notes as $note) :
                $content_img = preg_replace("/<img contenteditable=[^>]+\>/i", "*image 📷", $note->getContent());
                $content_clean = str_replace("<br>", " ", preg_replace("/<input[^>]+\>/i", "", $content_img));
                $content_no_emoji = preg_replace("/<img[^>]+\>/i", "", $content_clean);
            ?>
                <tr>
                    <?php if (strlen($note->getTitle()) >= 30) : ?>
                        <td><?= substr($note->getTitle(), 0, 30) . "..." ?></td>
                    <?php else : ?>
                        <td><?= $note->getTitle() ?></td>
                    <?php endif ?>

                    <?php if (strlen($content_no_emoji) >= 100) : ?>
                        <td><?= substr(str_replace("<br>", " ", $content_clean), 0, 100) . "..." ?></td>
                    <?php else : ?>
                        <td><?= str_replace("<br>", " ", $content_clean) ?></td>
                    <?php endif ?>
                    <td class="table-btn" style="border-bottom-width: 0">
                        <a href="<?= $this->url('notes/view', ['id' => $note->getId()]) ?>" class="btn btn-primary">View</a>
                        <a href="<?= $this->url('notes/edit', ['id' => $note->getId()]) ?>" class="btn btn-success">Edit</a>
                        <button id="btn-delete" class="btn btn-danger" data-target="#deleteModal" data-toggle="modal" data-href="<?= $this->url('notes/delete', ['id' => $note->getId()]) ?>"><i class="fa-solid fa-trash-can"></i></button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <p style=" font-size: 21px;">There's no notes available, do you want to create one?</p>
    <a href="<?= $this->url('notes/create') ?>"><button class="btn btn-primary">Create note</button></a>
<?php endif ?>

<script src="<?= $this->basePath('js/list/index.js') ?>"></script>