<link rel="stylesheet" href="<?= $this->basePath('css/content_manipulation/index.css') ?>">

<h2>View Page</h2>

<?php
$content_clean =  preg_replace("/<input[^>]+\>/i", "", $note->getContent());
?>

<div class="container-buttons">
    <div class="buttons">
        <a href="<?= $this->url('notes/edit', ['id' => $note->getId()]) ?>" class="btn btn-info btn-edit-view">
            <i class="fa-solid fa-pen-to-square" style="color: white"></i>
        </a>
        <button id=" btn-delete" class="btn btn-danger" data-target="#deleteModal" data-toggle="modal" data-href="<?= $this->url('notes/delete', ['id' => $note->getId()]) ?>">
            <i class="fa-solid fa-trash-can"></i>
        </button>
    </div>
</div>

<div class="list-group">
    <div class="list-group-item" style="display: flex">
        <h5>Title:&nbsp </h5>
        <?= $note->getTitle() ?>
    </div>
    <div class="list-group-item">
        <h5>Content </h5>
        <?= $content_clean ?>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Are you sure you want to delete this item?</h5><button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
            </div>
            <input type="hidden" name="note_id" id="note_id" value="">
            <div class="modal-footer">
                <a id="dataConfirm"><button type="button" class="btn btn-danger">Delete</button></a>
                <button type="button" class="btn btn-primary" data-dismiss="modal" aria-label="Close">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#deleteModal').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget);
        var href_Id = button.data('href');
        $('#dataConfirm').attr('href', href_Id);
    })
</script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var txtarea = document.querySelector("textarea.form-control");
        txtarea.style.height = txtarea.scrollHeight + "px";
    });
</script>