<div class="row h-100 justify-content-center align-items-center">
    <?php

    $form->setAttribute('action', $this->url('user/login'));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    <div class="form-group">
        <h3 class="title">Login</h3>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('email'));
        ?>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('username'));
        ?>
        <div class="checkbox">
            <label>
                <?= $this->formElement($form->get('remember_me')); ?> Remember me?
            </label>
        </div>
    </div>
    <div class="form-group">
        <?php
        echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
</div>