<?php
if ($isLogged) :
    echo 'username de quem está logado: ' . $isLogged;
?>

    <div>ESTOU LOGADO</div>
<?php else :
?>
    <div>NÃO ESTOU LOGADO</div>
<?php endif; ?>
<div class="row h-100 justify-content-center align-items-center">
    <?php

    $form->setAttribute('action', $this->url('auth', ['action' => 'login']));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    <div class="form-group">
        <h3 class="title">Login</h3>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('email'));
        ?>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('username'));
        ?>
        <div class="checkbox">
            <label>
                <?= $this->formElement($form->get('remember_me')); ?> Remember me?
            </label>
        </div>
    </div>
    <div class="form-group">
        <?php
        echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
</div>