<?= $this->headTitle('Login - Notes') ?>

<div class="center-form">
    <?php

    $form->setAttribute('action', $this->url('user/login'), 'style', 'width:"auto"');
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    <div class="form-group form-title">
        <h3 class="title">Login</h3>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('email'));
        ?>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('username'));
        ?>
        <div class="checkbox">
            <label>
                <?= $this->formElement($form->get('remember_me')); ?> Remember me?
            </label>
        </div>
    </div>
    <div class="form-group">
        <?php
        echo $this->formSubmit($form->get('submit'));
        ?>
    </div>

</div>