<h2>Página do perfil</h2>

<div class="list-group">

    <div class="list-group-item" style="display: flex">
        <h5>Username:&nbsp </h5>
        <?= $user['username'] ?>
    </div>
    <div class="list-group-item" style="display: flex">
        <h5>Email:&nbsp </h5>
        <?= $user['email'] ?>
    </div>

    <div class="list-group-item" style="display: flex">
        <h5>Name:&nbsp </h5>
        <?= $user['firstName'] . ' ' . $user['lastName'] ?>
    </div>