<div class="center-form">

    <?php
    $form->setAttribute('action', $this->url('user/register'));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    ?>
    <div class="form-group form-title">
        <h3 class="title">Sign up</h3>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('username'));
        ?>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('firstName'));
        ?>
    </div>
    <div class="form-group">
        <?php

        echo $this->formRow($form->get('lastName'));
        ?>
    </div>
    <div class="form-group">
        <?php
        echo $this->formRow($form->get('email'));
        ?>
    </div>
    <div class="form-group">
        <?php
        echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
</div>