<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    <script src="https://kit.fontawesome.com/20b10c76ff.js" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <!-- Scripts -->
    <?= $this->headScript() ?>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/popper.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/Rti-logo.png') ?>" class="nav-logo" alt="Laminas">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item active" style="display:flex">
                        <a class="nav-link" href="<?= $this->url('home') ?>">
                            Home <span class="sr-only">(current)</span>
                        </a>

                        <?php if ($this->identity()) : ?>
                            <a class="nav-link" href="<?= $this->url('notes/list') ?>">
                                Notes<span class="sr-only"></span>
                            </a>
                            <div class="nav-link dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Account
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" href="<?= $this->url('user/profile') ?>">Profile</a></li>
                                    <li><a class="dropdown-item" href="<?= $this->url('user/logout') ?>">Log out</a></li>
                                </ul>
                            </div>
                        <?php else : ?>

                            <a class="nav-link btn btn-primary" href="<?= $this->url('user/login') ?>">
                                Sign In <span class="sr-only"></span>
                            </a>
                            <a class="nav-link btn btn-info" href="<?= $this->url('user/register') ?>">
                                Sign Up <span class="sr-only"></span>
                            </a>
                        <?php endif ?>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?php
        $flashMessenger = $this->flashMessenger();
        if ($flashMessenger->hasSuccessMessages()) {
            echo "<ul>";
            foreach ($flashMessenger->getSuccessMessages() as $message) {
                echo "<li class='alert alert-success'>" . $message . "</li>";
            }
            echo "</ul>";
        }

        if ($flashMessenger->hasErrorMessages()) {
            echo "<ul>";
            foreach ($flashMessenger->getErrorMessages() as $message) {
                echo "<li class='alert alert-danger'>" . $message . "</li>";
            }
            echo "</ul>";
        }
        ?>
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="https://www.linkedin.com/company/rti-tech" target="_blank">R:TI tech Project</a>
            </p>
        </footer>
    </div>

    <script>
        $(document).ready(function() {
            $(".alert").fadeIn(300).delay(2500).fadeOut(400);
        });
    </script>
</body>

</html>