<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item active" style="display:flex">
                        <a class="nav-link" href="<?= $this->url('home') ?>">
                            Home <span class="sr-only">(current)</span>
                        </a>

                        <?php if ($this->identity()) : ?>
                            <a class="nav-link" href="">
                                Notes<span class="sr-only"></span>
                            </a>
                            <a class="nav-link" href="">
                                Profile<span class="sr-only"></span>
                            </a>
                            <a class="nav-link" href="<?= $this->url('user/logout') ?>">
                                Log out<span class="sr-only"></span>
                            </a>
                        <?php else : ?>
                            <a class="nav-link" href="<?= $this->url('user/login') ?>">
                                Sign In <span class="sr-only"></span>
                            </a>
                            <a class="nav-link" href="<?= $this->url('user/register') ?>">
                                Sign Up <span class="sr-only"></span>
                            </a>
                        <?php endif ?>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?php
        $flashMessenger = $this->flashMessenger();
        if ($flashMessenger->hasSuccessMessages()) {
            echo "<ul>";
            foreach ($flashMessenger->getSuccessMessages() as $message) {
                echo "<li class='alert alert-success'>" . $message . "</li>";
            }
            echo "</ul>";
        }

        if ($flashMessenger->hasErrorMessages()) {
            echo "<ul>";
            foreach ($flashMessenger->getErrorMessages() as $message) {
                echo "<li class='alert alert-danger'>" . $message . "</li>";
            }
            echo "</ul>";
        }
        ?>
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>

</html>